-- MySQL Script generated by Transformo Framework
-- Thursday, April 28, 2022 00:27:54

--      David Romero Organvidez
--      Technical Researcher
--      drorganvidez@us.es
--      University of Seville

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Schema basemigrada
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `basemigrada` ;
CREATE SCHEMA IF NOT EXISTS `basemigrada` DEFAULT CHARACTER SET UTF8MB4 ;
USE `basemigrada` ;


-- -----------------------------------------------------
-- Table  `basemigrada`.`post`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `basemigrada`.`post` ;
CREATE TABLE IF NOT EXISTS `basemigrada`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(25)  NOT NULL,
  `body` TEXT  NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;

INSERT INTO `basemigrada`.`post` 
  SELECT * FROM `base1`.`post` ;

-- -----------------------------------------------------
-- Table  `basemigrada`.`post_meta`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `basemigrada`.`post_meta` ;
CREATE TABLE IF NOT EXISTS `basemigrada`.`post_meta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(25)  NOT NULL,
  post_id INT,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (post_id) REFERENCES post (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;

INSERT INTO `basemigrada`.`post_meta` 
  SELECT * FROM `base1`.`post_meta` ;

-- -----------------------------------------------------
-- Table  `basemigrada`.`comment`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `basemigrada`.`comment` ;
CREATE TABLE IF NOT EXISTS `basemigrada`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;

INSERT INTO `basemigrada`.`comment` 
  SELECT * FROM `base1`.`comment` ;

-- -----------------------------------------------------
-- Table  `basemigrada`.`comment2`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `basemigrada`.`comment2` ;
CREATE TABLE IF NOT EXISTS `basemigrada`.`comment2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;

INSERT INTO `basemigrada`.`comment2` 
  SELECT * FROM `base1`.`comment2` ;

-- -----------------------------------------------------
-- Transformation  CreateEntityAction
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `basemigrada`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;

-- -----------------------------------------------------
-- Transformation  CreateEntityAction
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `basemigrada`.`comment2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;

