-- MySQL Script generated by Transformo Framework
-- Thursday, April 21, 2022 13:56:14

--      David Romero Organvidez
--      Technical Researcher
--      drorganvidez@us.es
--      University of Seville

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Schema example
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `example` ;
CREATE SCHEMA IF NOT EXISTS `example` DEFAULT CHARACTER SET utf8 ;
USE `example` ;


-- -----------------------------------------------------
-- Table  `example`.`post`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `example`.`post` ;
CREATE TABLE IF NOT EXISTS `example`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(25)  NOT NULL,
  `body` TEXT  NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `example`.`post` SELECT * FROM `base1`.`post` ;

-- -----------------------------------------------------
-- Table  `example`.`post_meta`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `example`.`post_meta` ;
CREATE TABLE IF NOT EXISTS `example`.`post_meta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(25)  NOT NULL,
  id_post_meta INT,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (id_post_meta) REFERENCES post (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `example`.`post_meta` SELECT * FROM `base1`.`post_meta` ;

-- -----------------------------------------------------
-- Transformation  ChangeAuthorType
-- -----------------------------------------------------

ALTER TABLE `example`.`post_meta`
  MODIFY COLUMN `author` VARCHAR(100);

-- -----------------------------------------------------
-- Transformation  RenameAuthorName
-- -----------------------------------------------------

ALTER TABLE `example`.`post_meta`
  RENAME COLUMN `author` TO `owner`;

-- -----------------------------------------------------
-- Transformation  DeleteAuthor
-- -----------------------------------------------------

ALTER TABLE `example`.`post_meta`
  DROP COLUMN `owner`;

-- -----------------------------------------------------
-- Transformation  CreateSummary
-- -----------------------------------------------------

ALTER TABLE `example`.`post_meta`
  ADD COLUMN `summary` TEXT;

-- -----------------------------------------------------
-- Transformation  MoveBody
-- -----------------------------------------------------

ALTER TABLE `example`.`post_meta`
  ADD COLUMN `body` TEXT;

INSERT INTO `example`.`post_meta` (`body`) 
  SELECT `body` FROM `base1`.`post`;

ALTER TABLE `example`.`post`
  DROP COLUMN `body`;

