-- MySQL Script generated by Transformo Framework
-- Tuesday, April 19, 2022 17:44:29

--      David Romero Organvidez
--      Technical Researcher
--      drorganvidez@us.es
--      University of Seville

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Schema example
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `example` ;
CREATE SCHEMA IF NOT EXISTS `example` DEFAULT CHARACTER SET utf8 ;
USE `example` ;


-- -----------------------------------------------------
-- Table  `example`.`post`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `example`.`post` ;
CREATE TABLE IF NOT EXISTS `example`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(25)  NOT NULL,
  `body` TEXT  NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table  `example`.`post_meta`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `example`.`post_meta` ;
CREATE TABLE IF NOT EXISTS `example`.`post_meta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(25)  NOT NULL,
  id_post_meta INT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (id_post_meta) REFERENCES post (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Transformation  ChangeAuthorType
-- -----------------------------------------------------

ALTER TABLE `example`.`post_meta`
MODIFY COLUMN `author` VARCHAR(100);

-- -----------------------------------------------------
-- Transformation  ChangeAuthorName
-- -----------------------------------------------------

ALTER TABLE `example`.`post_meta`
RENAME COLUMN `author` TO `owner`;

-- -----------------------------------------------------
-- Transformation  DeleteAuthor
-- -----------------------------------------------------

ALTER TABLE `example`.`post_meta`
DROP COLUMN `owner`;

